### ISSUE TITLE
React to UI code move

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#1]
All UI code is about to be moved out of [core](https://github.com/iTwin/itwinjs-core) into [appui](https://github.com/iTwin/appui). 

```[tasklist]
### Tasks
- [x] https://github.com/iTwin/presentation/issues/2
- [x] https://github.com/iTwin/presentation/issues/8
- [x] https://github.com/iTwin/presentation/issues/4
- [x] https://github.com/iTwin/presentation/issues/16
- [x] https://github.com/iTwin/presentation/issues/13
- [x] https://github.com/iTwin/presentation/issues/25
- [x] https://github.com/iTwin/presentation/issues/14
- [x] https://github.com/iTwin/presentation/issues/3
- [x] https://github.com/iTwin/presentation/issues/31
- [x] https://github.com/iTwin/presentation/issues/38
- [x] https://github.com/iTwin/presentation/issues/15
- [ ] https://github.com/iTwin/presentation/issues/40
- [ ] https://github.com/iTwin/presentation/issues/43
- [ ] https://github.com/iTwin/presentation/issues/42
```

**Comment by grigasp** [comment]
All items done
