### ISSUE TITLE
Investigate using background workers

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#241]
We want to make sure our hierarchy building code doesn't block the main thread. Need to check if our code is costly and if it is - make it possible to execute it in a background worker (while still supporting execution without a worker for easier testing and debugging).
```[tasklist]
### Tasks
- [x] Investigate if there's any Main thread blocking, when loading 1k, 10k, 100k, 1M nodes with various groupings. Add report into this issue.
- [x] Name bottlenecks, identify possible areas of improvement.
- [x] Link optimizations made along the way with this issue.
```

**Comment by JonasDov** [comment]
Report from the investigation:
[Report.xlsx](https://github.com/iTwin/presentation/files/14239804/Report.xlsx)
Didn't add information about loading 1M nodes, because it was taking too long (tried loading ~650k nodes, that took ~25 mins).
The main thread is blocked in all cases: with 1k, 10k, 100k and 1M nodes.

**Comment by JonasDov** [comment]
Bottlenecks:
1. `modifyModel` takes a lot of time when loading large amount of nodes, this blocks the main thread. 
 How to improve: Instead of loading all the nodes, load them page by page.

2. `getSchemaJSON` API is sometimes called multiple times with the same request body. Every time the response comes in, it has to be processed, this causes the main thread to be blocked for every response. 
 How to improve: 1) Remove additional request calls; 2) change `RpcRequest.submit` to run on a background worker.

3. `hierarchyProvider.getNodes` function takes the most amount of time, during which, the main thread is blocked. 
 How to improve: Execute this function on a background worker.

**Comment by grigasp** [comment]
Closing in favor of https://github.com/iTwin/presentation/issues/425, which tracks implementation of running expensive tasks in a background worker.
