### ISSUE TITLE
Purpose of the class selector is unclear

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#251]
The are only a few clues on the purpose of the class selector:
- Placeholder: "Select class..."
- The fact that selecting a property fills the class selector with classes. It's not exactly clear what the classes mean. 

In addition, we don't actually use the classes as listed in the selector, e.g. the following workflow doesn't work:
1. Select property `X` that exists on classes `A` and `B` -> class selector is filled with both classes.
2. Remove class `A` from class selector.
3. Hit "Apply" - the results contain instances of both classes, although I'd expected `A` ones to be filtered out.

```[tasklist]
### Tasks
- [x] Add a "Reset" button to clear all filters in the dialog (https://github.com/iTwin/presentation/pull/356)
- [x] "Apply" button should always be enabled (https://github.com/iTwin/presentation/pull/356)
- [x] Property operator should be reset when property selection changes (https://github.com/iTwin/appui/pull/619)
- [x] Property picker should show a union of selected class properties rather than intersection (https://github.com/iTwin/presentation/pull/358)
- [x] The fact that picking a class is optional should be more obvious (https://github.com/iTwin/presentation/pull/362)
- [x] Resulting filter should contain information about selected classes (https://github.com/iTwin/presentation/pull/363)
- [ ] Property rules should be cleared when selected class list is changed (https://github.com/iTwin/presentation/pull/371)
```

**Comment by grigasp** [comment]
Note: if the selected class is used for filtering, then we should make sure "Apply" button is enabled when no property filters are specified (but a class is selected).
