### ISSUE TITLE
`hierarchies`: Training material

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#423]
Add training material for using `@itwin/presentation-hierarchies` package to create hierarchies.

```[tasklist]
### Tasks
- [ ] https://github.com/iTwin/presentation/pull/667
- [ ] https://github.com/iTwin/presentation/pull/665
- [ ] https://github.com/iTwin/presentation/pull/672
- [ ] https://github.com/iTwin/presentation/pull/675
- [ ] https://github.com/iTwin/presentation/pull/678
- [ ] https://github.com/iTwin/presentation/pull/682
- [ ] https://github.com/iTwin/presentation/pull/679
- [ ] https://github.com/iTwin/presentation/pull/680
- [ ] https://github.com/iTwin/presentation/pull/685
- [ ] https://github.com/iTwin/presentation/pull/690
```
