### ISSUE TITLE
`@itwin/unified-selection`

### ISSUE THREAD

**Issue by grigasp** [iTwin/presentation#452]
Need to set up a package for managing [unified selection](https://www.itwinjs.org/presentation/unified-selection/).

**API requirements:**
- Two types of "selectables":
  - ECInstance: full class name + ECInstance id.
  - Custom: unique identifier + async ecinstance keys loader + custom data.
- Create unified selection storage that stores "selectables" by iModel and selection level.
- Modify selection storage: replace / add / remove / clear.
- Listening to selection changes.
- Getting hilite set for given "selectables" and for active selection.
```[tasklist]
### Tasks
- [x] https://github.com/iTwin/presentation/pull/460
- [x] https://github.com/iTwin/presentation/pull/466
- [ ] https://github.com/iTwin/presentation/pull/488
- [ ] https://github.com/iTwin/presentation/pull/482
- [ ] https://github.com/iTwin/presentation/pull/491
- [ ] https://github.com/iTwin/itwinjs-core/pull/6545
```
