### ISSUE TITLE
`@itwin/presentation-hierarchies-react`

### ISSUE THREAD

**Issue by saskliutas** [iTwin/presentation#465]
Need to set up a package for working with stateless hierarchies builder in react.
```[tasklist]
### Tasks
- [ ] https://github.com/iTwin/presentation/pull/474
- [ ] https://github.com/iTwin/presentation/pull/478
- [ ] https://github.com/iTwin/presentation/pull/511
```
